import './globals.css'
import { Inter } from 'next/font/google'
import { TareasProvedor } from '@/context/TasksContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <TareasProvedor>
           {children}
        </TareasProvedor>
       
        
        </body>
    </html>
  )
}
